[versions]
kotlinpoet-version = "2.2.0"
kotlinx-coroutines-core = "1.10.2"
kotlinx-coroutines-test = "1.10.2"
lib_kotlinx-serialization-json = "1.9.0"
lib_bitcoinj-core = "0.16"
lib_bcprov-jdk15to18 = "1.82"
lib_junit-bom = "5.13.4"
lib_androidx = "1.5.0"
lifecycle-common = "2.9.4"
okhttp = "5.1.0"
kotlin-gradle-plugin = "2.2.20"
jetbrains-kotlin-jvm = "2.2.20"
swagger-parser = "2.1.34"

[libraries]
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "lifecycle-common" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-common" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlinx-serialization-json = {group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "lib_kotlinx-serialization-json"}
bitcoinj-core = { group = "org.bitcoinj", name = "bitcoinj-core", version.ref = "lib_bitcoinj-core"}
bcprov-jdk15to18 = { group = "org.bouncycastle", name = "bcprov-jdk15to18", version.ref = "lib_bcprov-jdk15to18"}
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "lib_junit-bom"}
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher"}
androidx-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "lib_androidx" }
androidx-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref ="lib_androidx" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
squareup-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet-version" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger-parser" }

[plugins]
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrains-kotlin-jvm" }